Traceback (most recent call last):
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\laragon\bin\python\python-3.10\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\laragon\bin\python\python-3.10\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nursery_dataset = _deepnote_execute_sql('SELECT * FROM `nursery`.`nursery`', 'SQL_69180BE6_4514_45E9_A13B_52B1406EF574', audit_sql_comment='', sql_cache_mode='cache_disabled')
nursery_dataset
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[5], line 1[0m
[1;32m----> 1[0m nursery_dataset [38;5;241m=[39m [43m_deepnote_execute_sql[49m([38;5;124m'[39m[38;5;124mSELECT * FROM `nursery`.`nursery`[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSQL_69180BE6_4514_45E9_A13B_52B1406EF574[39m[38;5;124m'[39m, audit_sql_comment[38;5;241m=[39m[38;5;124m'[39m[38;5;124m'[39m, sql_cache_mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcache_disabled[39m[38;5;124m'[39m)
[0;32m      2[0m nursery_dataset

[1;31mNameError[0m: name '_deepnote_execute_sql' is not defined

